basic_settings:
  site_title: Ataul Munim
  site_tagline: Android GDE and Android at Monzo.
  favicon_image: /images/favicon.png

header_settings:
  avatar_image: /images/avatar.png
  logo_image: 

social_settings:
  facebook_url: ''
  twitter_url: 'https://twitter.com/ataulm'
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: 'https://medium.com/@ataulm'
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: 'https://github.com/ataulm'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@400;600&display=swap" rel="stylesheet">'

advanced_settings:
  ajax_loading: false # Google Analytics is fudging up with ajax
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""